### ISSUE TITLE
Error while creating object

### ISSUE THREAD

**Issue by lormayna** [micropython-IMU/micropython-bmp180#10]
Hello,
I am trying to use the BMP180 to read temperature and pressure on ESP8266.
When I try to instantiate the object I got this error:

`>>> bus = I2C(scl=Pin(12), sda=Pin(13), freq=100000) 
>>> bmp180=BMP180(bus)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bmp180.py", line 47, in __init__
OSError: [Errno 110] ETIMEDOUT`

Could you help me solving the issue?
Thank you

**Comment by faithhunja** [comment]
I'd suggest using RTC with your ESP8266.

**Comment by faithhunja** [comment]
Got the same error, then realized I had a loose connection. Even after fixing that, the error was still there. However, I burnt the firmware again onto the ESP8266 and it worked well.
