### ISSUE TITLE
Troubles reading temperature

### ISSUE THREAD

**Issue by lucasvinals** [micropython-IMU/micropython-bmp180#9]
Hi, first of all, excelent library! Helps a lot to get started with MicroPython and the ESP8266...

For some reason, I'm having troubles to make this work...Whenever I read temperature, I get the following error:

``>>> bmp.temperature``
``Traceback (most recent call last):``
  ``File "<stdin>", line 1, in <module>``
  ``File "bmp180.py", line 141, in temperature``
``ZeroDivisionError: divide by zero``

The problem is in line 141, inside temperature method, which is: 
`X2 = self._MC*2**11/(X1+self._MD)`

that **(X1+self._MD)** is equal to zero, then it breaks the division... 

I would appreciate it greatly if you could help me to identify that reading problem

Thanks again,

Luke

**Comment by timm-zz** [comment]
I encountered the same problem. Have you solved this problem?

**Comment by RossiFin** [comment]
I encountered the same problem. Bug was on my code. At start I initialized variables to zero. Fixed divided by zero error by not initializing temp variable beforehand.
